name: Build docker image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@v1.2.1
        name: lint
        with:
          dockerfile: Dockerfile
      - name: Publish to Docker Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v1
        with:
          repository: tarkilhk/simplelogin-postfix-docker
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          tag_with_ref: true
